### ISSUE TITLE
"Please refresh table" command

### ISSUE THREAD

**Issue by KirstieJane** [all-contributors/app#157]
**Is your feature request related to a problem? Please describe.**

In my project, I've decided to list contributors in alphabetical order. At the moment the best work around is to manually shuffle the `.all-contributorsrc` file into the order that I want and then ask the bot to re-add an entry that is already there. This behaviour should open a new PR with a re-generated table.

Thank you to @jakebolam for suggesting this workaround! https://github.com/all-contributors/all-contributors/issues/225#issuecomment-469695838

**Describe the solution you'd like**

As @jakebolam suggests, it would be great to have a little command to regenerate the table without adding new entries. Something like `@bot please refresh the table` would make sense.

**Describe alternatives you've considered**

The workaround above is absolutely fine, so this isn't a high priority, but it isn't very intuitive for new users.

**Additional context**

I love the bot so freaking much. THANK YOU for all the awesome work ✨ 💖

**Comment by jakebolam** [comment]
Thanks for the suggestion @KirstieJane.

If you wanted to implement yourself we would be here to help.

**Comment by KirstieJane** [comment]
Ah, yes, unfortunately I don't know any javascript so I think I'd be entirely lost in trying to code this up 😬 

Sorry to be no help. As I said, I don't think this is a really high priority, but worth having here in case someone who *does* know how to update the code wants to implement it ✨

**Comment by brosaplanella** [comment]
I would be keen on implementing this issue but I have no experience with javascript. If you can point me to the right file, I would be happy to try to contribute.

PS: I also tried the workaround but didn't work for me. In fact, I think there is an issue (see [my reply here](https://github.com/all-contributors/app/pull/346#issuecomment-940001793)) because if you ask the bot to add someone and don't merge the PR, then it doesn't let you add that same contribution for that person later on.

**Comment by tenshiAMD** [comment]
Duplicate https://github.com/all-contributors/app/issues/62
