### ISSUE TITLE
Cannot Add Contributor

### ISSUE THREAD

**Issue by kjxbyz** [all-contributors/app#262]
[repo](https://github.com/chenyifaerfans/fafaer-blog)

**Describe the bug**
We had trouble processing your request. Please try again later.

**Screenshots**
<img width="1558" alt="WeChat424553c573708d405f79ba4546079292" src="https://user-images.githubusercontent.com/47768002/69491008-2f6bd480-0eca-11ea-8632-a5bcf87b43fa.png">

**Comment by b3u** [comment]
same

**Comment by jakebolam** [comment]
There are 3 bugs generating sentry issues. I believe this may be related to: https://github.com/all-contributors/all-contributors-bot/issues/140

**Comment by CSRedRat** [comment]
I have some trouble: https://github.com/CSRedRat/topalias/pull/4
will try without .allcontributorsrc and with .allcontributorsrc

**Comment by krzkaczor** [comment]
In case the bot still behaves funny for you guys, I create a GitHub Action that pushes new contributors directly to the repo: https://github.com/actionwareio/all-contributors-action

**Comment by gr2m** [comment]
Hey @krzkaczor, I'll do some work on the all-contributors app starting next week. I'd prefer we join forces and fix the existing problems in the app together instead of doubling our efforts and splitting the user base?

**Comment by krzkaczor** [comment]
Hey @gr2m! 

Don't get me wrong but I think that GitHub Action is superior to the bot. Mostly because merging directly to the main branch creates an amazing UX. I am not saying that my particular GHA is superior 😆  but generally - with GHA you can make a better UX in this case. However, I get that sometimes users don't use GitHub Actions so bots will be still useful.

That being said, I would love to cooperate in this space. First of all, I would be more than happy to move https://github.com/actionwareio/all-contributors-action into @all-contributors org and make it one of the "official" ways to use @all-contributors.

Secondly, there is a huge opportunity for code reuse between a bot and an action. Things like comment parsing, interacting with CLI (which I believe, should be remade into SDK btw), are both reimplemented at this point.

Let me know what do you think.

Cheers!

**Comment by gr2m** [comment]
> there is a huge opportunity for code reuse between a bot and an action. Things like comment parsing, interacting with CLI (which I believe, should be remade into SDK btw), are both reimplemented at this point.

Definitely. Let me take some time to look into the app code right now. My main goal is to make it simple to maintain and to contirbute to, which also means I'll make it more decomposable. That's what I did with @octokit and @probot, which are the underlying tools that app is built upon. I'll keep you posted.

> Don't get me wrong but I think that GitHub Action is superior to the bot

Well I wouldn't say superior, but different. It's good to offer both choices. Thanks for offering to move the action to the all-contributors organization, that's a good idea

**Comment by tenshiAMD** [comment]
@kjxbyz @CSRedRat is this still relevant today?  Have you checked this using the latest version? Please check and let us know if this still occurs. Closing this for now. Thanks! 🎉
