### ISSUE TITLE
my .all-contributorsrc changes but README.md doesn't change

### ISSUE THREAD

**Issue by teddylee777** [all-contributors/app#325]
**Describe the bug**
Once I comment
@all-contributors add <someone> as a contributor on code

then, it produces 2 files, 
- .all-contributorsrc
- README.md

It works well with .all-contributorsrc file, but it doesn't update README.md file

Once I review README.md changes, then it shows 'there is no change'

my repo is 

https://github.com/teddylee777/machine-learning

**Comment by Berkmann18** [comment]
1. What version of the bot are you using?
2. Where was this comment done? If it was on a PR, was it as part of a review?

**Comment by amit-sharma** [comment]
I am using the latest version, since I installed it on my github account a few days back. I got it fixed now, here's what I did. 

The error was because I had just changed the file from README.md to a custom file in my repo. The bot was not finding any boilerplate template markdown code in that new file. When I copied the initial bot-generated markdown code from README.md to my custom file, it started working. Seems related to this issue: https://github.com/all-contributors/all-contributors-bot/issues/201
