### ISSUE TITLE
Loss of all-contributors.rc and empty pr when user already exists

### ISSUE THREAD

**Issue by hertzg** [all-contributors/app#336]
This is the continuation of the other issues after solving #332 

The `README` issue is gone 🎉  but seems like now other issues appeared:

* When I requested to add myself for something new the bot created a pr with totally new .all-contributors (removed everyone else)

This was probably because it did not fetch the local git from origin/upstream master because the commit from where it branched of is `15 commits behind master`.
![image](https://user-images.githubusercontent.com/1886698/103479015-c0e68f00-4dca-11eb-8171-039b0f634941.png)

* After when I requested for someone else who already exists in the list it seems to have fetched the latest commit before pushing but the changelog is empty.

![image](https://user-images.githubusercontent.com/1886698/103479073-49652f80-4dcb-11eb-8f2a-dba0db61dfb2.png)

![image](https://user-images.githubusercontent.com/1886698/103479051-128f1980-4dcb-11eb-92e0-de4defd9f1cc.png)

Please have a look here: https://github.com/hertzg/node-net-keepalive/issues/152

**Comment by gr2m** [comment]
Thanks George, I'm looking into it.

So far I tried to reproduce the problem here: https://github.com/gr2m/sandbox/issues/163, but to no avail. I created one PR that adds a new contribution type to an existing contributor (https://github.com/gr2m/sandbox/pull/166/files) and one PR that adds a new contributor, both correctly updated the existing files

I'll continue to digg into it

**Comment by gr2m** [comment]
Okay I know what is happening. A pull request is created, but the branch still exists from a previous pull request.

See my thread here: https://github.com/gr2m/node-net-keepalive/issues/1

The first pull request created via https://github.com/gr2m/node-net-keepalive/issues/1#issuecomment-754096552 did add two comments to a branch that still existed

The 2nd pull request created via https://github.com/gr2m/node-net-keepalive/issues/1#issuecomment-754098882 after I deleted the `all-contributors/add-hertzg` branch.

The fix is to make sure we delete a branch if it still exists. Would you like to try send a pull request to resolve the problem?

**Comment by gr2m** [comment]
The problem seems to be that we only check if the branch exists, without taking into account if an open pull request exists for the branch or not.

https://github.com/all-contributors/app/blob/263a04c386033ee36315f786a0a9efddc22150a2/lib/setup-repository.js#L10-L14

That check is not enough. If the branch exists, we need to check if an open pull request exists. If there is an open pull request, set the base branch as we currently do. Otherwise delete the existing branch and do not set the base branch

**Comment by hertzg** [comment]
Sure I can whip up a pr for that 👍
